/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessapp;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Nicole
 */
public class MealPlan extends javax.swing.JFrame {
    
    private JComboBox<String> mealDropdown;
    private JComboBox<String> dayDropdown;
    private JButton RecipeButton;
    
    /**
     * Creates new form MealPlan
     */
    public MealPlan() {
        initComponents();
        initCustomComponents();
    }
    
    private void initCustomComponents() {
        
        String[] mealType = {"Breakfast", "Lunch", "Dinner", "Snack"};
        mealDropdown = new JComboBox<>(mealType);
        mealDropdown.setBounds(50, 150, 150, 30);
        
        String[] mealDays = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
        dayDropdown = new JComboBox<>(mealDays);
        dayDropdown.setBounds(220, 150, 150, 30);
        
        RecipeButton = new JButton("Show Recipe");
        RecipeButton.setBounds(150, 200, 120, 30);
        
        RecipeButton.addActionListener((ActionEvent e) -> {
            showRecipe();
        });
        
        orangebg.add(mealDropdown);
        orangebg.add(dayDropdown);
        orangebg.add(RecipeButton);
    }
    
    private void showRecipe() {
        String selectedMeal = (String) mealDropdown.getSelectedItem();
        String selectedDay = (String) dayDropdown.getSelectedItem();
        String recipe = getRecipeForMeal(selectedMeal, selectedDay);
        JOptionPane.showMessageDialog(this, recipe, selectedMeal + "Recipe for " + selectedDay, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private String getRecipeForMeal(String meal, String day) {
        String recipe = " ";
        recipe = switch (meal) {
            case "Breakfast" -> getBreakfastRecipe(day);
            case "Lunch" -> getLunchRecipe(day);
            case "Dinner" -> getDinnerRecipe(day);
            case "Snack" -> getSnackRecipe(day);
            default -> "No recipe available.";
        };
        return recipe;
    }
    
    private String getBreakfastRecipe(String day) {
        return switch (day) {
            case "Monday" -> "Oatmeal with bananas.";
            case "Tuesday" -> "Scrambled eggs with spinach.";
            case "Wednesday" -> "Greek yogurt with honey and nuts.";
            case "Thursday" -> "Smoothie with berries and spinach.";
            case "Friday" -> "Avocado toast with poached egg.";
            case "Saturday" -> "Pancakes with maple syrup.";
            case "Sunday" -> "Chia seed pudding with fruits.";
            default -> "No recipe available.";
        };
    }
    
    private String getLunchRecipe(String day) {
        return switch (day) {
            case "Monday" -> "Quinoa salad with chickpeas.";
            case "Tuesday" -> "Grilled chicken wrap.";
            case "Wednesday" -> "Vegetable stir-fry with tofu.";
            case "Thursday" -> "Turkey sandwich with avocado.";
            case "Friday" -> "Pasta salad with pesto.";
            case "Saturday" -> "Lentil soup with bread.";
            case "Sunday" -> "Caesar salad with shrimp.";
            default -> "No recipe available.";
        };
    }

    private String getDinnerRecipe(String day) {
        return switch (day) {
            case "Monday" -> "Baked salmon with asparagus.";
            case "Tuesday" -> "Chicken curry with rice.";
            case "Wednesday" -> "Stuffed bell peppers.";
            case "Thursday" -> "Beef tacos with salsa.";
            case "Friday" -> "Vegetable lasagna.";
            case "Saturday" -> "Grilled steak with vegetables.";
            case "Sunday" -> "Roast chicken with potatoes.";
            default -> "No recipe available.";
        };
    }

    private String getSnackRecipe(String day) {
        return switch (day) {
            case "Monday" -> "Hummus with carrot sticks.";
            case "Tuesday" -> "Apple slices with peanut butter.";
            case "Wednesday" -> "Trail mix with nuts and dried fruits.";
            case "Thursday" -> "Greek yogurt with granola.";
            case "Friday" -> "Rice cakes with almond butter.";
            case "Saturday" -> "Popcorn with nutritional yeast.";
            case "Sunday" -> "Dark chocolate with strawberries.";
            default -> "No recipe available.";
        };
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orangebg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        menubutton = new javax.swing.JLabel();
        mealplan = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        Searchbox = new javax.swing.JTextField();
        notif = new javax.swing.JLabel();
        pfp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        tab = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(395, 682));

        orangebg.setBackground(new java.awt.Color(255, 152, 63));
        orangebg.setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(171, 220, 229));

        menubutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N

        mealplan.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        mealplan.setText("Meal Plan");

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        Searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchboxActionPerformed(evt);
            }
        });

        notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notif.png"))); // NOI18N

        pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menubutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mealplan)
                .addGap(48, 48, 48)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mealplan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(menubutton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(notif, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pfp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(171, 220, 229));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N

        tab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabs.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(tab)
                .addGap(71, 71, 71)
                .addComponent(home)
                .addGap(67, 67, 67)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab)
                    .addComponent(back)
                    .addComponent(home))
                .addContainerGap())
        );

        banner.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        banner.setText("Welcome to your Meal Plan!");

        javax.swing.GroupLayout orangebgLayout = new javax.swing.GroupLayout(orangebg);
        orangebg.setLayout(orangebgLayout);
        orangebgLayout.setHorizontalGroup(
            orangebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(orangebgLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(banner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orangebgLayout.setVerticalGroup(
            orangebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangebgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orangebg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orangebg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void SearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchboxActionPerformed

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MealPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MealPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MealPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MealPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MealPlan().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Searchbox;
    private javax.swing.JLabel back;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mealplan;
    private javax.swing.JLabel menubutton;
    private javax.swing.JLabel notif;
    private javax.swing.JPanel orangebg;
    private javax.swing.JLabel pfp;
    private javax.swing.JLabel search;
    private javax.swing.JLabel tab;
    // End of variables declaration//GEN-END:variables
}
